# Generated by Django 4.2.1 on 2023-05-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customaccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customaccount',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
