# Generated by Django 4.2.1 on 2023-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_damagedunit_laptop_userinfo_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
